"""CHANGELOG.md generator: regenerated from data/history snapshots.

Simplest correct option: each run rebuilds the changelog by diffing
consecutive history snapshots (oldest → newest), so it stays consistent
with the recorded history even if a run is skipped.
"""

from __future__ import annotations

from pathlib import Path

from ..diffing import diff_data
from ..store import list_history_snapshots, load_snapshot


def generate_changelog(history_dir: Path | None = None) -> str:
    snapshots = list_history_snapshots(history_dir) if history_dir else list_history_snapshots()
    lines: list[str] = []
    lines.append("# Changelog")
    lines.append("")
    lines.append(
        "Auto-generated by TokenMiner from `data/history/` snapshots. "
        "Do not edit by hand — regenerate with `python -m tokenminer generate`."
    )
    lines.append("")

    if not snapshots:
        lines.append("_No history snapshots yet._")
        lines.append("")
        return "\n".join(lines)

    entries: list[tuple[str, list[str]]] = []
    prev = None
    for path in snapshots:
        providers, offers, models = load_snapshot(path)
        if prev is None:
            date = path.stem
            entries.append((date, [
                f"Baseline snapshot: {len(providers)} providers, "
                f"{len(offers)} offers, {len(models)} free models",
            ]))
        else:
            old_p, old_o, old_m = prev
            changes = diff_data(old_p, providers, old_o, offers, old_m, models)
            if changes:
                # Plain text only: the ``## {date}`` header already carries
                # the date and +/-/⚠ symbols would duplicate the bullet.
                entries.append((path.stem, [c.text for c in changes]))
        prev = (providers, offers, models)

    for date, items in reversed(entries):  # newest first
        lines.append(f"## {date}")
        lines.append("")
        for item in items:
            lines.append(f"- {item}")
        lines.append("")
    return "\n".join(lines)
